export {
  BASELINE_LEVEL,
  CLOSE_ANIMATION_MS,
  DEFAULT_BARS,
  DEFAULT_LANGUAGE,
  MAX_TRANSCRIPT_LENGTH,
  SILENCE_THRESHOLD,
  SPEECH_CONFIG,
  WAVEFORM_SHIFT_INTERVAL_MS,
} from "./voiceRecorder";
